---
:dev:
  :reports:
  - :no_tasks
  - :blocked
  - :not_approved
  - :rejected
  - :dcut
  :summary_email: libra-devel@redhat.com
:qe:
  :reports:
  - :not_qe_ready
  - :rejected
  :summary_email: libra-qe@redhat.com
  :nag_owners: false
