#!/bin/bash

source $OPENSHIFT_CARTRIDGE_SDK_BASH

function update_configuration {
    set +u
    if [[ -f /usr/bin/scl ]] && /usr/bin/scl -l | grep -q 'mongodb24'
    then
        local pe=""
        local env_dir="${OPENSHIFT_MONGODB_DIR}/env"

        local syspath="/bin:/usr/bin"
        local sclpath=$(PATH="$syspath" scl enable mongodb24 'printenv PATH')
        pe="${sclpath%:$syspath}"
        if [[ -n "${pe}" ]]
        then
            set_env_var 'OPENSHIFT_MONGODB_PATH_ELEMENT' "${pe}" $env_dir
        fi
        local ld_path=$(LD_LIBRARY_PATH="" /usr/bin/scl enable mongodb24 "printenv LD_LIBRARY_PATH")
        if [[ -n "${ld_path}" ]]
        then
            set_env_var 'OPENSHIFT_MONGODB_LD_LIBRARY_PATH_ELEMENT' "${ld_path}" $env_dir
        fi
        local man_path=$(MANPATH="" /usr/bin/scl enable mongodb24 "printenv MANPATH")
        path_append ${MANPATH:-:} ${man_path:-:} > ${env_dir}/MANPATH
    fi
}

function mongodb_context {
    if [[ -n "${OPENSHIFT_MONGODB_PATH_ELEMENT}" ]] # SCL mongo is installed
    then
        /usr/bin/scl enable mongodb24 "$1"
    else
        eval $1
    fi
}
