# Countries:
#   Add any additional country information here.
#   The accepted countries are based on config/environments/*
#
#   Links are provided to help find appropriate values per country)
#     subdivision_name: http://en.wikipedia.org/wiki/Table_of_administrative_divisions_by_country
#     postal_code_name: http://en.wikipedia.org/wiki/Postal_code#Terms
---
:additional_info:
  CA:
    :subdivision_name: Province
    :postal_code_name: Postal Code
  DE:
    :subdivision_name: State
  US:
    :subdivision_name: State
    :postal_code_name: ZIP
:defaults:
  :subdivision_name: Region
  :postal_code_name: Postcode
