# If this file changes, you must modify server-common/openshift/streamline.rb to reflect the changes
---
:email_confirm_url: confirm.html
:lost_password_url: resetPassword.html
:change_password_url: protected/changePassword.html
:login_url: login.html
:register_url: registration.html
:request_access_url: requestAccess.html
:roles_url: cloudVerify.html
:user_info_url: userInfo.html
:acknowledge_terms_url: protected/acknowledgeTerms.html
:unacknowledged_terms_url: "protected/findUnacknowledgedTerms.html?hostname=openshift.redhat.com&context=OPENSHIFT&locale=en"
