# The format of this file should be
#--- 
#:host: openshift.com
#:hosts: 
#- ex-srv1.stg.rhcloud.com 
#- ex-srv2.stg.rhcloud.com 
--- 
:host: "openshift.com"
:hosts: 
- "10.1.2.3"
- "10.2.3.4"
:template: "https://%s/status"
