development:
  sessions:
    default:
      database: localhost
      hosts:
        - localhost:27017
      user: openshift
      password: mooo
test:
  sessions:
    default:
      database: localhost
      hosts:
        - localhost:27017
      user: openshift
      password: mooo